server:
  port: 8001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lctravel?serverTimezone=GMT
    username: root
    password: DWD1506839375

mybatis:
  config-location: classpath:sqlMapConfig-spring.xml
  #mapper-locations: classpath:com.travel.mapper/*Mapper.xml

zookeeper:
  address: 127.0.0.1:2181
  timeout: 4000